const ITEMS = {
	"Rock" : "res://Resources/Cards/rock.tres",
	"Strike" : "res://Resources/Cards/strike.tres",
	"Shield Block" : "res://Resources/Cards/shield_block.tres",
	#"Shift Stance" : "res://Resources/Cards/shift_stance.tres",
	"Hardened Skin" : "res://Resources/Cards/hardened_skin.tres", 
	#"Boulder" : "res://Resources/Cards/boulder.tres",
	"Daunting Shout" : "res://Resources/Cards/daunting_shout.tres",
	"Swarm" : "res://Resources/Cards/swarm.tres",
	"Strengthen" : "res://Resources/Cards/strengthen.tres",
	#"Double Up" : "res://Resources/Cards/double_up.tres",
	"Seethe" : "res://Resources/Cards/seethe.tres",
	"Constrict" : "res://Resources/Cards/constrict.tres",
	"Bite" : "res://Resources/Cards/bite.tres",
	"Run Away" : "res://Resources/Cards/run_away.tres",
	"Charge" : "res://Resources/Cards/charge.tres",
	"Fireball" : "res://Resources/Cards/fireball.tres",
	"Incantation Fireball" : "res://Resources/Cards/incantation_fireball.tres",
	"Bolster" : "res://Resources/Cards/bolster.tres"
}
